### ISSUE TITLE
Aggro window solution. 

### ISSUE THREAD

**Issue by AeoluxTwitch** [Niitek/LUI-WotLK#1]
First of all, I'm so glad that I found your github, I'm a huge fan of Lui v3 since 3.3.5a, so yeah, has been some years, and I just joined TBC classic and was missing my old UI :(

I just installed and for now you just did an amazing job, congrats. 

I've realized that we don't have omen threat window, since Omen is not compatible with TBC Classic, I was thinking that maybe you can link with that a Details Tiny Threat window, that would do the work, I don't know if you're capable of doing it, but it is just an idea. 

Anyway I'm so thankful for your job, do you have any kind of tip jar? I would like to support you :D

**Comment by Niitek** [comment]
In the options, you can already link the TPS frame to details! I am actively working on bug fixes and issue, so spot any let me know.

and as far as a tip jar, I do!
https://ko-fi.com/nitsah

**Comment by AeoluxTwitch** [comment]
Thank you, I just discovered few mins before you posted it, long time no playing/not using Lui v3 xD

Anyway should I post everything on issues, or do you have any other feedback way? ^^
