### ISSUE TITLE
Installation failed due to nil value @Vuhdo

### ISSUE THREAD

**Issue by 56shish56** [Niitek/LUI-WotLK#11]
Message: Interface\AddOns\LUI\LUI.lua:572: attempt to call method 'InstallVudho' (a nil value)
Time: Sun Apr 10 18:54:56 2022
Count: 2
Stack: Interface\AddOns\LUI\LUI.lua:572: attempt to call method 'InstallVudho' (a nil value)
[string "@Interface\AddOns\LUI\LUI.lua"]:572: in function <Interface\AddOns\LUI\LUI.lua:551>

Locals: self = install_frame {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @Interface\SharedXML\Backdrop.lua:144
 Center = <unnamed> {
 }
 GetBackdropColor = <function> defined @Interface\SharedXML\Backdrop.lua:382
 SetupTextureCoordinates = <function> defined @Interface\SharedXML\Backdrop.lua:206
 OnBackdropSizeChanged = <function> defined @Interface\SharedXML\Backdrop.lua:174
 HasBackdropInfo = <function> defined @Interface\SharedXML\Backdrop.lua:270
 SetBackdropBorderColor = <function> defined @Interface\SharedXML\Backdrop.lua:414
 RightEdge = <unnamed> {
 }
 backdropInfo = <table> {
 }
 BottomEdge = <unnamed> {
 }
 GetEdgeSize = <function> defined @Interface\SharedXML\Backdrop.lua:180
 BottomLeftCorner = <unnamed> {
 }
 BottomRightCorner = <unnamed> {
 }
 TopEdge = <unnamed> {
 }
 ApplyBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:286
 SetBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:321
 ClearBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:274
 TopRightCorner = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @Interface\SharedXML\Backdrop.lua:401
 GetBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:339
 TopLeftCorner = <unnamed> {
 }
 SetupPieceVisuals = <function> defined @Interface\SharedXML\Backdrop.lua:238
 SetBackdropColor = <function> defined @Interface\SharedXML\Backdrop.lua:391
 LeftEdge = <unnamed> {
 }
 SetBorderBlendMode = <function> defined @Interface\SharedXML\Backdrop.lua:258
}
(*temporary) = nil
(*temporary) = <table> {
 defaults = <table> {
 }
 NewInputNumber = <function> defined @Interface\AddOns\LUI\devapi.lua:1010
 Profiler = <table> {
 }
 NewWidth = <function> defined @Interface\AddOns\LUI\devapi.lua:1056
 NewEnable = <function> defined @Interface\AddOns\LUI\devapi.lua:885
 UnregisterComm = <function> defined @Interface\AddOns\Masque\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 GetDefaultVal = <function> defined @Interface\AddOns\LUI\LUI.lua:685
 Lib = <table> {
 }
 SyncAddonVersion = <function> defined @Interface\AddOns\LUI\LUI.lua:317
 chatcommands = <table> {
 }
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 NewPosY = <function> defined @Interface\AddOns\LUI\devapi.lua:1036
 IsEnabled = <function> defined @Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 GetDBVar = <function> defined @Interface\AddOns\LUI\LUI.lua:659
 RegisterModule = <function> defined @Interface\AddOns\LUI\LUI.lua:1544
 Opposites = <table> {
 }
 UnregisterMessage = <function> defined @Interface\AddOns\Masque\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 Update = <function> defined @Interface\AddOns\LUI\LUI.lua:423
 hooks = <table> {
 }
 NewOffsetY = <function> defined @Interface\AddOns\LUI\devapi.lua:1044
 NewInput = <function> defined @Interface\AddOns\LUI\devapi.lua:992
 db = <table> {
 }
 Points = <table> {
 }
 UnregisterAllComm = <function> defined @Interface\AddOns\Masque\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 SetEnabledState = <function> defined @Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @Interface\AddOns\LUI\libs\AceHook-3.0\AceHook-3.0.lua:274
 InstallOmen = <function> defined @Interface\AddOns\LUI\addons\omen.lua:12
 OnEnable = <function> defined @Interface\AddOns\LUI\LUI.lua:1896
 FetchScript = <function> defined @Interface\AddOns\LUI\LUI.lua:774
 Module = <function> defined @Interface\AddOns\LUI\LUI.lua:606
 Media = <table> {
 }
 OnInitialize = <function> defined @Interface\AddOns\LUI\LUI.lua:1838
 NewModule = <function> defined @Interface\AddOns\Masque\Libs\

**Comment by Niitek** [comment]
Fixed with previous release.
