### ISSUE TITLE
Druid Player Combo Points do not work

### ISSUE THREAD

**Issue by evan-xie** [Niitek/LUI-WotLK#12]
Druid Player Combo Points do not work

**Comment by evan-xie** [comment]
edit 'LUI\unitframes\core\elements\classicons.lua ' line 223
`	
        if(PlayerClass` == 'ROGUE' or PlayerClass == 'DRUID') then
		ClassPowerID = Enum.PowerType.ComboPoints or 4
		ClassPowerType = 'COMBO_POINTS'

		if(PlayerClass == 'DRUID') then
			RequireForm = CAT_FORM
			--RequireSpell = 5221 -- Shred
		end
	end
`

**Comment by Niitek** [comment]
Issue fixed with hotfix 4.51
