### ISSUE TITLE
Missing info text on one account but not the other

### ISSUE THREAD

**Issue by drocks** [Niitek/LUI-WotLK#13]
The info text(gold, latency, etc) is working on one account but not the other. At one point I did copy my saved variables from one account to the other both ways after making changes. So not sure if that affected it but the one account has not been working at all.

**Comment by Niitek** [comment]
Try clearing your WTF, it's probs an issue with how the variables were moved.

**Comment by Niitek** [comment]
no response in over a month, assuming it was solved, closing issue.
