### ISSUE TITLE
Flash Light And Holy Light

### ISSUE THREAD

**Issue by Etherlane** [Niitek/LUI-WotLK#14]
Everytime I cast Flash Light and Holy light Paladin's skill in every single bar and all key. I got this error. I hope this can be fixed because it's so anoying it always pop up in an urgent situation.

Message: ...\AddOns\LUI\libs\LibHealComm-4.0\LibHealComm-4.0.lua:762: attempt to perform arithmetic on local 'requiresLevel' (a nil value)
Time: Fri Oct  7 07:56:01 2022
Count: 5
Stack: ...\AddOns\LUI\libs\LibHealComm-4.0\LibHealComm-4.0.lua:762: attempt to perform arithmetic on local 'requiresLevel' (a nil value)
[string "@Interface\AddOns\LUI\libs\LibHealComm-4.0\LibHealComm-4.0.lua"]:762: in function <...\AddOns\LUI\libs\LibHealComm-4.0\LibHealComm-4.0.lua:755>
[string "@Interface\AddOns\LUI\libs\LibHealComm-4.0\LibHealComm-4.0.lua"]:1073: in function <...\AddOns\LUI\libs\LibHealComm-4.0\LibHealComm-4.0.lua:1071>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\LUI\libs\LibHealComm-4.0\LibHealComm-4.0.lua"]:2248: in function `?'
[string "@Interface\AddOns\LUI\libs\LibHealComm-4.0\LibHealComm-4.0.lua"]:2702: in function <...\AddOns\LUI\libs\LibHealComm-4.0\LibHealComm-4.0.lua:2698>

Locals: spellData = <table> {
 levels = <table> {
 }
 averages = <table> {
 }
 coeff = 0.714286
}
spellName = "Holy Light"
spellRank = nil
average = nil
requiresLevel = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = 80
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on local 'requiresLevel' (a nil value)"
type = <function> defined =[C]:-1
min = <function> defined =[C]:-1
playerLevel = 80

**Comment by Niitek** [comment]
issue resolved with 3.46, closing issue.
