### ISSUE TITLE
Mousing over info txt

### ISSUE THREAD

**Issue by Litvan** [Niitek/LUI-WotLK#18]
Overall, this addon DESPERATELY needs some love for classic wotlk

chat edit box no longer on top despite being set in options, mini menu on top never hides, and I miss my side panels working

Date: 2023-01-18 08:59:09
ID: 15
Error occured in: Global
Count: 4
Message: Interface/AddOns/LUI/modules/tooltip.lua line 228:
   attempt to call method 'SetBackdrop' (a nil value)
Debug:
   [string "=(tail call)"]: ?
   [string "=[C]"]: SetBackdrop()
   [string "@Interface/AddOns/LUI/modules/tooltip.lua"]:228:
      Interface/AddOns/LUI/modules/tooltip.lua:224
   [string "=(tail call)"]: ?
   [string "=[C]"]: GameTooltip_UpdateStyle()
   [string "*GameTooltipTemplate.xml:359_OnTooltipCleared"]:3:
      [string "*GameTooltipTemplate.xml:359_OnTooltipClear..."]:1
   [string "=[C]"]: Hide()
   [string "@Interface/AddOns/HandyNotes_WrathOfTheLichKing/handler/handler.lua"]:1234:
      ...ns/HandyNotes_WrathOfTheLichKing/handler/handler.lua:1232
   [string "=[C]"]: ?
   [string "@Interface/AddOns/HandyNotes/HandyNotes.lua"]:56:
      Interface/AddOns/HandyNotes/HandyNotes.lua:51
   [string "@Interface/AddOns/HandyNotes/HandyNotes.lua"]:169: OnLeave()
   [string "@Interface/AddOns/HandyNotes/HandyNotes.lua"]:403:
      Interface/AddOns/HandyNotes/HandyNotes.lua:402
Locals:
(*temporary) = true
(*temporary) = <function> defined =[C]:-1

**Comment by Niitek** [comment]
A lot of the issues mentioned have been fixed for some time, closing issue to remove clutter.
