### ISSUE TITLE
I can't open my bags

### ISSUE THREAD

**Issue by M1steRny** [Niitek/LUI-WotLK#19]
I can't open my bags.

**To Reproduce:**
Start the game,
Login,
Press the inventory key,
Get the error.

**Expected behaviour:**
Open my bags.

**Error Logs:**

Message: Interface/AddOns/LUI/modules/bags.lua:717: Usage: local success = self:SetFont(fontFile, height, flags)
Time: Wed Jan 18 10:56:21 2023
Count: 1
Stack: Interface/AddOns/LUI/modules/bags.lua:717: Usage: local success = self:SetFont(fontFile, height, flags)

Locals: 

**Possible solution:**

Change:
GetContainerNumFreeSlots
to:
C_Container.GetContainerNumFreeSlots

Compatility between Retail and Classic:
(C_Container and C_Container.GetContainerNumFreeSlots or GetContainerNumFreeSlots)()

**Comment by M1steRny** [comment]
Some more error logs on another character:
Message: Interface/AddOns/LUI/modules/bags.lua:717: Usage: local success = self:SetFont(fontFile, height, flags)
Time: Wed Jan 18 11:12:51 2023
Count: 2
Stack: Interface/AddOns/LUI/modules/bags.lua:717: Usage: local success = self:SetFont(fontFile, height, flags)
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetFont'
[string "@Interface/AddOns/LUI/modules/bags.lua"]:717: in function `Layout'
[string "@Interface/AddOns/LUI/modules/bags.lua"]:1122: in function `ReloadLayout'
[string "@Interface/AddOns/LUI/modules/bags.lua"]:120: in function <Interface/AddOns/LUI/modules/bags.lua:118>
[string "=[C]"]: in function `Show'
[string "@Interface/AddOns/LUI/modules/bags.lua"]:168: in function <Interface/AddOns/LUI/modules/bags.lua:163>
[string "=(tail call)"]: ?
[string "TOGGLEBACKPACK"]:1: in function <[string "TOGGLEBACKPACK"]:1>

Locals: (*temporary) = "down"
(*temporary) = <function> defined =[C]:-1

**Comment by M1steRny** [comment]
Message: Interface/AddOns/LUI/modules/datatext.lua:304: attempt to call upvalue 'GetContainerNumFreeSlots' (a nil value)
Time: Wed Jan 18 11:15:40 2023
Count: 1
Stack: Interface/AddOns/LUI/modules/datatext.lua:304: attempt to call upvalue 'GetContainerNumFreeSlots' (a nil value)
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface/AddOns/LUI/modules/datatext.lua"]:304: in function `OnEnable'
[string "@Interface/AddOns/LUI/modules/datatext.lua"]:129: in function `Enable'
[string "@Interface/AddOns/LUI/modules/datatext.lua"]:2997: in function <Interface/AddOns/LUI/modules/datatext.lua:2992>
[string "@Interface/AddOns/LUI/modules/datatext.lua"]:4498: in function <Interface/AddOns/LUI/modules/datatext.lua:4496>
[string "=[C]"]: ?
[string "@Interface/AddOns/AngryAssignments/libs/AceAddon-3.0/AceAddon-3.0.lua"]:70: in function <.../AngryAssignments/libs/AceAddon-3.0/AceAddon-3.0.lua:65>
[string "@Interface/AddOns/AngryAssignments/libs/AceAddon-3.0/AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface/AddOns/AngryAssignments/libs/AceAddon-3.0/AceAddon-3.0.lua"]:540: in function `EnableAddon'
[string "@Interface/AddOns/AngryAssignments/libs/AceAddon-3.0/AceAddon-3.0.lua"]:630: in function <.../AngryAssignments/libs/AceAddon-3.0/AceAddon-3.0.lua:615>

Locals: <none>

**Comment by cephee** [comment]
Same for me +1

**Comment by Ayiadim** [comment]
There's a beta release that should fix most of the issues.

**Comment by Niitek** [comment]
Issue has been fixed in recent versions, closing thread
