### ISSUE TITLE
Target frame bug

### ISSUE THREAD

**Issue by AeoluxTwitch** [Niitek/LUI-WotLK#2]
![image](https://user-images.githubusercontent.com/85392835/120896149-8a829980-c620-11eb-8068-2be789426856.png)

Sometimes this happens and shows every raid icon in my frame, and the target frame just bugs out and shows blizzard one. I don't know exactly what forces this, but I've find the only solution reseting the profile, but this still happens sometimes.

**Comment by Niitek** [comment]
I have a feeling it has to do with the ghost wolf form, hotfix will come soon.

**Comment by Niitek** [comment]
new version out, will leave issue open for another day to see if it persists
