### ISSUE TITLE
LUI does not work properly since the patch.

### ISSUE THREAD

**Issue by Emelenzia123** [Niitek/LUI-WotLK#20]
Greetings,

I have some LUA messages since yesterday's patch and some things are not displayed because of it. I just post you all the messages from LUI

Message: Interface/SharedXML/FontableFrameMixin.lua:22: bad argument #3 to 'SetFont' (Usage: self:SetFont(fontFile, height, flags))
Time: Thu Jan 19 15:10:48 2023
Count: 1
Stack: Interface/SharedXML/FontableFrameMixin.lua:22: bad argument #3 to 'SetFont' (Usage: self:SetFont(fontFile, height, flags))
[string "=[C]"]: in function `SetFont'
[string "@Interface/AddOns/LUI/modules/chat/chat.lua"]:604: in function `LibSharedMedia_Registered'
[string "@Interface/AddOns/LUI/modules/chat/chat.lua"]:875: in function `Refresh'
[string "@Interface/AddOns/LUI/modules/chat/chat.lua"]:943: in function <Interface/AddOns/LUI/modules/chat/chat.lua:921>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/LUI/libs/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...erface/AddOns/LUI/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/LUI/libs/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/LUI/libs/AceAddon-3.0/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@Interface/AddOns/LUI/libs/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...erface/AddOns/LUI/libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: <none>

Message: Interface/AddOns/LUI/modules/chat/editbox.lua:167: bad argument #3 to 'SetFont' (Usage: local success = self:SetFont(fontFile, height, flags))
Time: Thu Jan 19 15:10:48 2023
Count: 1
Stack: Interface/AddOns/LUI/modules/chat/editbox.lua:167: bad argument #3 to 'SetFont' (Usage: local success = self:SetFont(fontFile, height, flags))
[string "=[C]"]: in function `SetFont'
[string "@Interface/AddOns/LUI/modules/chat/editbox.lua"]:167: in function `LibSharedMedia_Registered'
[string "@Interface/AddOns/LUI/modules/chat/editbox.lua"]:431: in function `Refresh'
[string "@Interface/AddOns/LUI/modules/chat/editbox.lua"]:456: in function <Interface/AddOns/LUI/modules/chat/editbox.lua:444>
[string "=[C]"]: ?
[string "@Interface/AddOns/LUI/libs/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...erface/AddOns/LUI/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/LUI/libs/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/LUI/libs/AceAddon-3.0/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@Interface/AddOns/LUI/libs/AceAddon-3.0/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@Interface/AddOns/LUI/libs/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...erface/AddOns/LUI/libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: <none>

Message: Usage: self:SetVertexColor(color [, a])
Time: Thu Jan 19 15:10:48 2023
Count: 1
Stack: Usage: self:SetVertexColor(color [, a])
[string "=[C]"]: in function `SetVertexColor'
[string "@Interface/SharedXML/Backdrop.lua"]:405: in function `SetBackdropColor'
[string "@Interface/AddOns/LUI/modules/minimap.lua"]:112: in function `SetMinimapFrames'
[string "@Interface/AddOns/LUI/modules/minimap.lua"]:217: in function `SetMinimap'
[string "@Interface/AddOns/LUI/modules/minimap.lua"]:897: in function <Interface/AddOns/LUI/modules/minimap.lua:892>
[string "=[C]"]: ?
[string "@Interface/AddOns/LUI/libs/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...erface/AddOns/LUI/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/LUI/libs/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/LUI/libs/AceAddon-3.0/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@Interface/AddOns/LUI/libs/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...erface/AddOns/LUI/libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: <none>

Message: Interface/AddOns/LUI/modules/datatext.lua:304: attempt to call upvalue 'GetContainerNumFreeSlots' (a nil value)
Time: Thu Jan 19 15:10:48 2023
Count: 1
Stack: Interface/AddOns/LUI/modules/datatext.lua:304: attempt to call upvalue 'GetContainerNumFreeSlots' (a nil value)
[string "@Interface/AddOns/LUI/modules/datatext.lua"]:304: in function `OnEnable'
[string "@Interface/AddOns/LUI/modules/datatext.lua"]:129: in function `Enable'
[string "@Interface/AddOns/LUI/modules/datatext.lua"]:2997: in function <Interface/AddOns/LUI/modules/datatext.lua:2992>
[string "@Interface/AddOns/LUI/modules/datatext.lua"]:4498: in function <Interface/AddOns/LUI/modules/datatext.lua:4496>
[string "=[C]"]: ?
[string "@Interface/AddOns/LUI/libs/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...erface/AddOns/LUI/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/LUI/libs/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/LUI/libs/AceAddon-3.0/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@Interface/AddOns/LUI/libs/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...erface/AddOns/LUI/libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: <none>

Message: Interface/AddOns/LUI/modules/panels.lua:387: attempt to call method 'SetGradientAlpha' (a nil value)
Time: Thu Jan 19 15:10:48 2023
Count: 1
Stack: Interface/AddOns/LUI/modules/panels.lua:387: attempt to call method 'SetGradientAlpha' (a nil value)
[string "@Interface/AddOns/LUI/modules/panels.lua"]:387: in function `Set'
[string "@Interface/AddOns/LUI/modules/panels.lua"]:665: in function `ApplyBackground'
[string "@Interface/AddOns/LUI/modules/panels.lua"]:638: in function <Interface/AddOns/LUI/modules/panels.lua:636>

Locals: f = LUIPanel_Raid {
 0 = <userdata>
 c = Texture {
 }
 bl = Texture {
 }
 l = Texture {
 }
 tr = Texture {
 }
 timerout = 0
 Set = <function> defined @Interface/AddOns/LUI/modules/panels.lua:300
 timerin = 0
 t = Texture {
 }
 AlphaIn = Frame {
 }
 tl = Texture {
 }
 r = Texture {
 }
 AlphaOut = Frame {
 }
 alphatimer = 0.500000
 frame = "oUF_LUI_raid"
 br = Texture {
 }
 b = Texture {
 }
}
d = "TOPLEFT"
p = oUF_LUI_raid {
 0 = <userdata>
}
w = 409
h = 181
s = 1
r = 0.950000
g = 0.860000
b = 0.160000
a = 0.400000
rc = 0.950000
gc = 0.860000
bc = 0.160000
ac = 0.400000
(*temporary) = nil
(*temporary) = Texture {
 0 = <userdata>
}
(*temporary) = "HORIZONTAL"
(*temporary) = 0.950000
(*temporary) = 0.860000
(*temporary) = 0.160000
(*temporary) = 0.400000
(*temporary) = 0.950000
(*temporary) = 0.860000
(*temporary) = 0.160000
(*temporary) = 0
(*temporary) = "attempt to call method 'SetGradientAlpha' (a nil value)"
fdir = "Interface\AddOns\LUI\media\templates\v3\"

Message: Interface/AddOns/LUI/modules/panels.lua:401: attempt to call method 'SetGradientAlpha' (a nil value)
Time: Thu Jan 19 15:10:48 2023
Count: 1
Stack: Interface/AddOns/LUI/modules/panels.lua:401: attempt to call method 'SetGradientAlpha' (a nil value)
[string "@Interface/AddOns/LUI/modules/panels.lua"]:401: in function `Set'
[string "@Interface/AddOns/LUI/modules/panels.lua"]:665: in function `ApplyBackground'
[string "@Interface/AddOns/LUI/modules/panels.lua"]:638: in function <Interface/AddOns/LUI/modules/panels.lua:636>

Locals: f = LUIPanel_Chat {
 0 = <userdata>
 c = Texture {
 }
 bl = Texture {
 }
 l = Texture {
 }
 tr = Texture {
 }
 timerout = 0
 Set = <function> defined @Interface/AddOns/LUI/modules/panels.lua:300
 timerin = 0
 t = Texture {
 }
 AlphaIn = Frame {
 }
 tl = Texture {
 }
 r = Texture {
 }
 AlphaOut = Frame {
 }
 alphatimer = 0.500000
 frame = "ChatAlphaAnchor"
 br = Texture {
 }
 b = Texture {
 }
}
d = "TOPRIGHT"
p = ChatAlphaAnchor {
 0 = <userdata>
}
w = 412
h = 177
s = 1
r = 0.950000
g = 0.860000
b = 0.160000
a = 0.400000
rc = 0.950000
gc = 0.860000
bc = 0.160000
ac = 0.400000
(*temporary) = nil
(*temporary) = Texture {
 0 = <userdata>
}
(*temporary) = "HORIZONTAL"
(*temporary) = 0.950000
(*temporary) = 0.860000
(*temporary) = 0.160000
(*temporary) = 0
(*temporary) = 0.950000
(*temporary) = 0.860000
(*temporary) = 0.160000
(*temporary) = 0.400000
(*temporary) = "attempt to call method 'SetGradientAlpha' (a nil value)"
fdir = "Interface\AddOns\LUI\media\templates\v3\"

These are all messages with all addons disabled except LUI

Here is a screenshot where you can see that the info texts at the top are not displayed and the MiniMap is not displayed correctly.

Also, the backgrounds of the panels are no longer visible and the TargetFrame shows only my own life and mana, neither the color/class of the target nor its health and mana.

Hopefully you can help me or bring an update for the current patch.

Kind regards,

Emelenzia123

![WoWScrnShot_011923_151510](https://user-images.githubusercontent.com/123086198/213466071-c09bd216-7337-434a-bdd5-b72fe7779d26.jpg)

**Comment by Ayiadim** [comment]
There's a beta release that should fix most of the issues.

**Comment by Niitek** [comment]
Issues have been fixed in recent versions, closing thread.
