### ISSUE TITLE
Error tracking Shaman weapon buffs

### ISSUE THREAD

**Issue by Mulcan1** [Niitek/LUI-WotLK#25]
Message: bad argument #2 to '?' (Usage: self:SetVertexColor(color [, a]))
Time: Fri Jan 27 13:56:23 2023
Count: 1
Stack: bad argument #2 to '?' (Usage: self:SetVertexColor(color [, a]))
[string "=[C]"]: in function `SetVertexColor'
[string "@Interface/AddOns/LUI/modules/auras/auras.lua"]:251: in function `Update'
[string "@Interface/AddOns/LUI/modules/auras/auras.lua"]:385: in function `UpdateWeaponEnchants'
[string "@Interface/AddOns/LUI/modules/auras/auras.lua"]:346: in function <Interface/AddOns/LUI/modules/auras/auras.lua:335>
[string "=[C]"]: ?

Locals: (*temporary) = "bad argument #2 to '?' (Usage: self:SetVertexColor(color [, a]))"

**Comment by Niitek** [comment]
Issues have been fixed in version 3.50.03, closing thread.
