### ISSUE TITLE
constantly error messages with TacoTip

### ISSUE THREAD

**Issue by LoopLouie** [Niitek/LUI-WotLK#27]
Hi, i just discovered LUi and i love the design. Just one big thing bothers me. When using the Addon TacoTip to show a Gearscore and other Tooltip based informations i receive every few seconds an LUI failure with this error message. 

...Tip/Libs/LibClassicInspector/LibClassicInspector.lua:3099: attempt to perform arithmetic on field '?' (a nil value)
Time: Tue Feb  7 21:48:31 2023
Count: 24
Stack: ...Tip/Libs/LibClassicInspector/LibClassicInspector.lua:3099: attempt to perform arithmetic on field '?' (a nil value)
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/TacoTip/Libs/LibClassicInspector/LibClassicInspector.lua"]:3099: in function <...Tip/Libs/LibClassicInspector/LibClassicInspector.lua:3083>
[string "@Interface/AddOns/TacoTip/Libs/LibClassicInspector/LibClassicInspector.lua"]:3157: in function <...Tip/Libs/LibClassicInspector/LibClassicInspector.lua:3153>

Locals: (*temporary) = <function> defined =[C]:-1

With this error constantly popping up TacoTip is not usable. I don´t know what the problem so maybe you improve the behaviour or add a feature to disable any Tooltip Actions vom LUI to get rid of any conflicts.

**Comment by Niitek** [comment]
I do not intend on adding compatibility with other mods I have no intention of using, you'll need to disable the tooltip module or TacoTip.
