### ISSUE TITLE
Unable to Open LUI Interface

### ISSUE THREAD

**Issue by shiroimin** [Niitek/LUI-WotLK#3]
When I try to open the LUI Interface I get this error:

Message: ...UI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:189: attempt to call method 'SetBackdrop' (a nil value)
Time: Mon Jun  7 15:30:16 2021
Count: 1
Stack: ...UI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:189: attempt to call method 'SetBackdrop' (a nil value)
[string "@Interface\AddOns\LUI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua"]:189: in function `?'
[string "@Interface\AddOns\LUI\libs\AceGUI-3.0\AceGUI-3.0.lua"]:108: in function <Interface\AddOns\LUI\libs\AceGUI-3.0\AceGUI-3.0.lua:97>
[string "@Interface\AddOns\LUI\libs\AceGUI-3.0\AceGUI-3.0.lua"]:146: in function `Create'
[string "@Interface\AddOns\LUI\libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1912: in function `Open'
[string "@Interface\AddOns\LUI\LUI.lua"]:1905: in function <Interface\AddOns\LUI\LUI.lua:1896>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\LUI\modules\micromenu.lua"]:428: in function <Interface\AddOns\LUI\modules\micromenu.lua:419>

Locals: frame = <unnamed> {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = <table> {
 bgFile = "Interface\DialogFrame\UI-DialogBox-Background"
 tileSize = 32
 edgeFile = "Interface\DialogFrame\UI-DialogBox-Border"
 tile = true
 edgeSize = 32
 insets = <table> {
 }
}
(*temporary) = "attempt to call method 'SetBackdrop' (a nil value)"
CreateFrame = <function> defined =[C]:-1
UIParent = UIParent {
 0 = <userdata>
 firstTimeLoaded = 1
 variablesLoaded = true
}
FrameBackdrop = <table> {
 bgFile = "Interface\DialogFrame\UI-DialogBox-Background"
 tileSize = 32
 edgeFile = "Interface\DialogFrame\UI-DialogBox-Border"
 tile = true
 edgeSize = 32
 insets = <table> {
 }
}
Frame_OnShow = <function> defined @Interface\AddOns\LUI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:28
Frame_OnClose = <function> defined @Interface\AddOns\LUI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:32
Frame_OnMouseDown = <function> defined @Interface\AddOns\LUI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:36
Button_OnClick = <function> defined @Interface\AddOns\LUI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:23
PaneBackdrop = <table> {
 bgFile = "Interface\ChatFrame\ChatFrameBackground"
 tileSize = 16
 edgeFile = "Interface\Tooltips\UI-Tooltip-Border"
 tile = true
 edgeSize = 16
 insets = <table> {
 }
}
StatusBar_OnEnter = <function> defined @Interface\AddOns\LUI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:71
StatusBar_OnLeave = <function> defined @Interface\AddOns\LUI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:75
Title_OnMouseDown = <function> defined @Interface\AddOns\LUI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:40
MoverSizer_OnMouseUp = <function> defined @Interface\AddOns\LUI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:45
SizerSE_OnMouseDown = <function> defined @Interface\AddOns\LUI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:56
SizerS_OnMouseDown = <function> defined @Interface\AddOns\LUI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:61
SizerE_OnMouseDown = <function> defined @Interface\AddOns\LUI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:66
Type = "Frame"
pairs = <function> defined =[C]:-1
methods = <table> {
 OnHeightSet = <function> defined @Interface\AddOns\LUI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:108
 OnRelease = <function> defined @Interface\AddOns\LUI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:93
 OnWidthSet = <function> defined @Interface\AddOns\LUI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:98
 SetStatusText = <function> defined @Interface\AddOns\LUI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:123
 OnAcquire = <function> defined @Interface\AddOns\LUI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:83
 Show = <function> defined @Interface\AddOns\LUI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:131
 EnableResize = <function> defined @Interface\AddOns\LUI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:135
 ApplyStatus = <function> defin

**Comment by Niitek** [comment]
what were you doing at the time? so I can try to reproduced the error.

**Comment by shiroimin** [comment]
Nothing. Just did a fresh install (deleted all of WTF folder except system config). No other addons installed or anything. Default Install nothing changed.

**Comment by Niitek** [comment]
And the install button works just fine, just won't open lui config?

**Comment by shiroimin** [comment]
Yup, the interface sets up no problem, everything is in place, but I also get LUA errors in other sections, like opening character sheet, Talent page, howering over friends/guilds in the upper right info panel.

**Comment by Niitek** [comment]
I wasn't able to reproduce the error, try the new version and see what happens. I will leave the issue open for another day or two.

**Comment by shiroimin** [comment]
I get this error now : 

Message: AceLocale-3.0: LUI: Missing entry for 'Welcome to LUI v3 for The Burning Crusade Classic'
Time: Tue Jun  8 07:40:58 2021
Count: 1
Stack: AceLocale-3.0: LUI: Missing entry for 'Welcome to LUI v3 for The Burning Crusade Classic'
[string "@Interface\AddOns\LUI\LUI.lua"]:831: in function <Interface\AddOns\LUI\LUI.lua:794>
[string "@Interface\AddOns\LUI\libs\AceConfig-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua"]:333: in function `app'
[string "@Interface\AddOns\LUI\libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1863: in function `Open'
[string "@Interface\AddOns\LUI\LUI.lua"]:1905: in function <Interface\AddOns\LUI\LUI.lua:1896>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\LUI\modules\micromenu.lua"]:428: in function <Interface\AddOns\LUI\modules\micromenu.lua:419>

Locals: <none>

**Comment by shiroimin** [comment]
It did fix the Guild databar error, partially the Friends bar. The friend bar does show data now, but will also give this error:

Message: Interface\AddOns\LUI\modules\datatext.lua:1419: bad argument #2 to 'format' (string expected, got boolean)
Time: Tue Jun  8 07:47:12 2021
Count: 4
Stack: Interface\AddOns\LUI\modules\datatext.lua:1419: bad argument #2 to 'format' (string expected, got boolean)
[string "=[C]"]: in function `format'
[string "@Interface\AddOns\LUI\modules\datatext.lua"]:1419: in function <Interface\AddOns\LUI\modules\datatext.lua:1379>
[string "@Interface\AddOns\LUI\modules\datatext.lua"]:1670: in function `Update'
[string "@Interface\AddOns\LUI\modules\datatext.lua"]:1896: in function `Anchor'
[string "@Interface\AddOns\LUI\modules\datatext.lua"]:2308: in function <Interface\AddOns\LUI\modules\datatext.lua:2305>

Locals: (*temporary) = "%1$s |cff%3$.2x%4$.2x%5$.2x- %2$s"
(*temporary) = "4385"
(*temporary) = true
(*temporary) = 255
(*temporary) = 204
(*temporary) = 0
(*temporary) = "string expected, got boolean"

**Comment by shiroimin** [comment]
It did also fix an error that would come up every time you changed area while flying. Also, let me know if you need any further info or pictures.

**Comment by Niitek** [comment]
3.35.01 has a fix for the localization, I didn't notice the flag at first when updating it. curseforge is crashing on me so you'll have to download it from here

**Comment by shiroimin** [comment]
Trying to open the LUI config gives the original error :

Message: ...UI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:189: attempt to call method 'SetBackdrop' (a nil value)
Time: Tue Jun  8 08:55:38 2021
Count: 1
Stack: ...UI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:189: attempt to call method 'SetBackdrop' (a nil value)
[string "@Interface\AddOns\LUI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua"]:189: in function `?'
[string "@Interface\AddOns\LUI\libs\AceGUI-3.0\AceGUI-3.0.lua"]:108: in function <Interface\AddOns\LUI\libs\AceGUI-3.0\AceGUI-3.0.lua:97>
[string "@Interface\AddOns\LUI\libs\AceGUI-3.0\AceGUI-3.0.lua"]:146: in function `Create'
[string "@Interface\AddOns\LUI\libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1912: in function `Open'
[string "@Interface\AddOns\LUI\LUI.lua"]:1905: in function <Interface\AddOns\LUI\LUI.lua:1896>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\LUI\modules\micromenu.lua"]:428: in function <Interface\AddOns\LUI\modules\micromenu.lua:419>

Locals: frame = <unnamed> {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = <table> {
 bgFile = "Interface\DialogFrame\UI-DialogBox-Background"
 tileSize = 32
 edgeFile = "Interface\DialogFrame\UI-DialogBox-Border"
 tile = true
 edgeSize = 32
 insets = <table> {
 }
}
(*temporary) = "attempt to call method 'SetBackdrop' (a nil value)"
CreateFrame = <function> defined =[C]:-1
UIParent = UIParent {
 0 = <userdata>
 firstTimeLoaded = 1
 variablesLoaded = true
}
FrameBackdrop = <table> {
 bgFile = "Interface\DialogFrame\UI-DialogBox-Background"
 tileSize = 32
 edgeFile = "Interface\DialogFrame\UI-DialogBox-Border"
 tile = true
 edgeSize = 32
 insets = <table> {
 }
}
Frame_OnShow = <function> defined @Interface\AddOns\LUI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:28
Frame_OnClose = <function> defined @Interface\AddOns\LUI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:32
Frame_OnMouseDown = <function> defined @Interface\AddOns\LUI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:36
Button_OnClick = <function> defined @Interface\AddOns\LUI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:23
PaneBackdrop = <table> {
 bgFile = "Interface\ChatFrame\ChatFrameBackground"
 tileSize = 16
 edgeFile = "Interface\Tooltips\UI-Tooltip-Border"
 tile = true
 edgeSize = 16
 insets = <table> {
 }
}
StatusBar_OnEnter = <function> defined @Interface\AddOns\LUI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:71
StatusBar_OnLeave = <function> defined @Interface\AddOns\LUI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:75
Title_OnMouseDown = <function> defined @Interface\AddOns\LUI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:40
MoverSizer_OnMouseUp = <function> defined @Interface\AddOns\LUI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:45
SizerSE_OnMouseDown = <function> defined @Interface\AddOns\LUI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:56
SizerS_OnMouseDown = <function> defined @Interface\AddOns\LUI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:61
SizerE_OnMouseDown = <function> defined @Interface\AddOns\LUI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:66
Type = "Frame"
pairs = <function> defined =[C]:-1
methods = <table> {
 OnHeightSet = <function> defined @Interface\AddOns\LUI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:108
 OnRelease = <function> defined @Interface\AddOns\LUI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:93
 OnWidthSet = <function> defined @Interface\AddOns\LUI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:98
 SetStatusText = <function> defined @Interface\AddOns\LUI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:123
 OnAcquire = <function> defined @Interface\AddOns\LUI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:83
 Show = <function> defined @Interface\AddOns\LUI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:131
 EnableResize = <function> defined @Interface\AddOns\LUI\libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:135
 ApplyStatus = <function> defin

**Comment by shiroimin** [comment]
Ok, I apologize. After your last fix, I didn't delete the WTF folder which did fix the LUI config issue and the other ones as well. Thank you so much for fixing it and bringing this UI to TBC. I missed it so much from back in the day.
