### ISSUE TITLE
SoD FocusFrame

### ISSUE THREAD

**Issue by ssg3Davins** [Niitek/LUI-WotLK#31]
FocusFrame does not exist in Classic_Era, so have to check if it exists. Otherwise it bricks other things on init, like Target of Target, Party Frame, Raid Frame.
in hideblizzard.lua changing the focus function works.
focus = function()
	if FocusFrame then
		FocusFrame:UnregisterAllEvents()
		FocusFrame:Hide()
	end
end,

**Comment by Niitek** [comment]
issue has been resolved in version 3.6
