### ISSUE TITLE
Keybindings

### ISSUE THREAD

**Issue by shiroimin** [Niitek/LUI-WotLK#5]
The "Keybindings" feature is not allowing me to bind any keys.

**Comment by Niitek** [comment]
I will take a look at the error and see about getting the rest of the bars stuff working, in the mean time you can use Bartender, LUI will move/skin all the bars for you.

**Comment by shiroimin** [comment]
Great. I don't get an error, just nothing happens. Thank you for the Bartender suggestion, that works great. Thank you :).

PS
Up to you if you want to close this ticket.

**Comment by Niitek** [comment]
Fixed with 3.38

**Comment by Kohrinthian** [comment]
I just downloaded 3.4, and keybindings are not working... I can't set a keybinding, and any I had previously worked for a brief moment, but when I went to adjust where a keybinding was... EVERY SINGLE keybinding I previously had, vanished... nothing works for keybindings.

**Comment by Niitek** [comment]
> I just downloaded 3.4, and keybindings are not working... I can't set a keybinding, and any I had previously worked for a brief moment, but when I went to adjust where a keybinding was... EVERY SINGLE keybinding I previously had, vanished... nothing works for keybindings.

Did you download the latest release from curse?

**Comment by Kohrinthian** [comment]
I downloaded the latest version from wow interface I think, I'll download
from curse.
