### ISSUE TITLE
Unitframes Fader - power level trigger

### ISSUE THREAD

**Issue by StuFuu** [Niitek/LUI-WotLK#6]
Unitframes Fader is not affected by changing the "Power Is Low" checkbox, because of that you cannot get the frame to Fade In while mana is low. All other parts of Fader module works perfectly fine, including "Health Is Low" which should work similar but doesn not. The moment my health hits 100% the frame fades out, even while mana is still not full.
![image](https://user-images.githubusercontent.com/23261673/121808507-1fa51400-cc59-11eb-804d-921a7203c30f.png)
![image](https://user-images.githubusercontent.com/23261673/121808557-4ebb8580-cc59-11eb-8594-b945650dac1b.png)
![image](https://user-images.githubusercontent.com/23261673/121808521-3186b700-cc59-11eb-8dea-947830dac277.png)

Edit: I will just add that i'm forcing global settings with health and power triggers both set to 100%

**Comment by Niitek** [comment]
Fixed with 3.38
