### ISSUE TITLE
when opening bag after doing mailbox

### ISSUE THREAD

**Issue by Sal-inja** [Niitek/LUI-WotLK#8]
This error keeps coming up after I open a mail item and it goes into my bag. I have Masque and LUI up to dated.

Message: Interface\AddOns\LUI\modules\bags.lua:283: attempt to compare number with nil
Time: Mon Aug  2 16:52:54 2021
Count: 3
Stack: Interface\AddOns\LUI\modules\bags.lua:283: attempt to compare number with nil
[string "@Interface\AddOns\LUI\modules\bags.lua"]:283: in function `SlotUpdate'
[string "@Interface\AddOns\LUI\modules\bags.lua"]:905: in function `Layout'
[string "@Interface\AddOns\LUI\modules\bags.lua"]:1135: in function `ReloadLayout'
[string "@Interface\AddOns\LUI\modules\bags.lua"]:120: in function <Interface\AddOns\LUI\modules\bags.lua:118>
[string "=[C]"]: in function `Show'
[string "@Interface\AddOns\LUI\modules\bags.lua"]:168: in function <Interface\AddOns\LUI\modules\bags.lua:163>
[string "=(tail call)"]: ?
[string "TOGGLEBACKPACK"]:1: in function <[string "TOGGLEBACKPACK"]:1>

Locals: self = <table> {
 NewToggle = <function> defined @Interface\AddOns\LUI\devapi.lua:407
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:367
 NewInputNumber = <function> defined @Interface\AddOns\LUI\devapi.lua:532
 CheckBagsCopy = <function> defined @Interface\AddOns\LUI\modules\bags.lua:1119
 EnableModule = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 NewEnable = <function> defined @Interface\AddOns\LUI\devapi.lua:421
 IterateEmbeds = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:442
 BagType = <function> defined @Interface\AddOns\LUI\modules\bags.lua:426
 SecureHookScript = <function> defined @Interface\AddOns\Bartender4\libs\AceHook-3.0\AceHook-3.0.lua:410
 BagFrameSlotNew = <function> defined @Interface\AddOns\LUI\modules\bags.lua:331
 EnableBags = <function> defined @Interface\AddOns\LUI\modules\bags.lua:929
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 defaultModuleState = true
 NewExecute = <function> defined @Interface\AddOns\LUI\devapi.lua:498
 IsEnabled = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 DisableModule = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:350
 NewColorNoAlpha = <function> defined @Interface\AddOns\LUI\devapi.lua:686
 CopyBags = <function> defined @Interface\AddOns\LUI\modules\bags.lua:1099
 RegisterMessage = <function> defined @Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 NewHeader = <function> defined @Interface\AddOns\LUI\devapi.lua:391
 hooks = <table> {
 }
 BAG_UPDATE_DELAYED = <function> defined @Interface\AddOns\LUI\modules\bags.lua:1026
 NewInput = <function> defined @Interface\AddOns\LUI\devapi.lua:518
 db = <table> {
 }
 InitSelect = <function> defined @Interface\AddOns\LUI\modules\bags.lua:199
 SetEnabledState = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @Interface\AddOns\Bartender4\libs\AceHook-3.0\AceHook-3.0.lua:274
 enabledState = true
 RegisterEvent = <function> defined @Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 Layout = <function> defined @Interface\AddOns\LUI\modules\bags.lua:701
 NewPosition = <function> defined @Interface\AddOns\LUI\devapi.lua:581
 NewGroup = <function> defined @Interface\AddOns\LUI\devapi.lua:338
 IterateModules = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:437
 RawHook = <function> defined @Interface\AddOns\Bartender4\libs\AceHook-3.0\AceHook-3.0.lua:313
 PLAYERBANKSLOTS_CHANGED = <function> defined @Interface\AddOns\LUI\modules\bags.lua:1004
 ITEM_LOCK_CHANGED = <function> defined @Interface\AddOns\LUI\modules\bags.lua:1030
 Enable = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:294
 NewModule = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0

**Comment by Niitek** [comment]
Unable to reproduce.
